#!/usr/bin/env bash
# One-time setup after creating a project from this template.
# Replaces placeholder strings with your actual project details.
#
# Usage: bash scripts/init.sh

set -euo pipefail

# ── Portable in-place sed (GNU sed needs no suffix arg; BSD/macOS sed needs '') ──
if sed --version 2>/dev/null | grep -q GNU; then
  sedi() { sed -i "$@"; }
else
  sedi() { sed -i '' "$@"; }
fi

# ── Guards ───────────────────────────────────────────────────────────────────
[[ -f go.mod ]] || { echo "Error: run this script from the repo root."; exit 1; }

grep -q "your-org/your-project" go.mod || { echo "Already initialised — go.mod no longer contains the placeholder."; exit 0; }

# ── Prompt ──────────────────────────────────────────────────────────────────
read -rp "GitHub org or username (e.g. acme): " GH_ORG
read -rp "Repository / project name (e.g. my-app): " PROJECT_NAME

[[ "$GH_ORG"      =~ ^[a-zA-Z0-9_-]+$ ]] || { echo "Invalid org name — only letters, numbers, hyphens, underscores."; exit 1; }
[[ "$PROJECT_NAME" =~ ^[a-zA-Z0-9_-]+$ ]] || { echo "Invalid project name — only letters, numbers, hyphens, underscores."; exit 1; }

MODULE="github.com/${GH_ORG}/${PROJECT_NAME}"

echo ""
echo "Will set:"
echo "  Go module  : ${MODULE}"
echo "  npm name   : ${PROJECT_NAME}-frontend"
echo ""
read -rp "Looks good? [y/N] " CONFIRM
[[ "${CONFIRM}" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 1; }

# ── Replacements ─────────────────────────────────────────────────────────────
sedi "s|github.com/your-org/your-project|${MODULE}|g" go.mod CLAUDE.md

# .golangci.yml gci import-grouping prefix must match the module path.
sedi "s|github.com/your-org/your-project|${MODULE}|g" .golangci.yml

sedi "s|your-project-frontend|${PROJECT_NAME}-frontend|g" frontend/package.json

# Project name in non-Go files.
sedi "s|your-project API|${PROJECT_NAME} API|g" api/openapi.yaml
sedi "s|your-project|${PROJECT_NAME}|g" README.md frontend/index.html frontend/src/App.vue

# Replace the module path in every Go source file.
while IFS= read -r -d '' f; do
  sedi "s|github.com/your-org/your-project|${MODULE}|g" "$f"
done < <(find . -type f -name '*.go' -print0)

# Replace the OTel service-name default (runs after module-path replacement so
# the broader s|your-project| pattern doesn't accidentally touch import paths).
sedi "s|envDefault:\"your-project\"|envDefault:\"${PROJECT_NAME}\"|g" internal/config/config.go

# The config test asserts the same default — keep it in sync or the test
# suite fails immediately after initialisation.
sedi "s|defaultServiceName = \"your-project\"|defaultServiceName = \"${PROJECT_NAME}\"|" internal/config/config_test.go

# Container image names in the deployment playbook.
sedi "s|ghcr.io/your-org/your-project|ghcr.io/${GH_ORG}/${PROJECT_NAME}|g" .ai/architecture/deployment.md

# ── Verification ─────────────────────────────────────────────────────────────
# Catch placeholders added to the template after this script was last updated.
# Only git-tracked files matter: build artifacts and IDE state are gitignored,
# and frontend/package-lock.json is regenerated by npm install (step 1 below).
LEFTOVERS="$(git grep -l "your-project\|your-org" -- \
  ':!scripts/init.sh' ':!frontend/package-lock.json' || true)"
if [[ -n "${LEFTOVERS}" ]]; then
  echo ""
  echo "WARNING: unreplaced placeholders remain in:"
  echo "${LEFTOVERS}"
  echo "Update scripts/init.sh to cover them, then re-run the relevant sed by hand."
fi

echo ""
echo "Done. Next steps:"
echo "  1. cd frontend && npm install   (generates a fresh package-lock.json)"
echo "  2. go test ./...                (verify the rename left everything green)"
echo "  3. git add -A && git commit -m 'chore: initialise project from template'"
